<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <span class="zdt-toolbar-info">DEMO EVENTs</span>
    </div>
    <div class="zdt-toolbar-detail zdt-toolbar-detail-redundant">
        <span class="zdt-toolbar-info zdt-toolbar-info-redundant">
            <span class="zdt-detail-label">Tests</span>
            <span class="zdt-detail-value">test-<?php echo $this->collector->getName(); ?></span>
        </span>
    </div>
</div>